### PR TITLE
add types to index.js

### PR DESCRIPTION
**Pull request by przemyslawjanpietrzak**

### CODE REVIEW

**Comment by feross** [comment]
Isn't this missing the entry in `package.json`?

**Comment by paambaati** [comment]
> Isn't this missing the entry in `package.json`?

This has been addressed in https://github.com/feross/fromentries/pull/21. @przemyslawjanpietrzak I hope you don't mind me reusing your PR.

**Comment by przemyslawjanpietrzak** [comment]
@paambaati glad to help :)

**Comment by feross** [comment]
#21 has been merged.

**Pull request closed without merging**
